/**
 * Generate SQLite Schema from PostgreSQL Schema
 * This script converts the PostgreSQL schema to SQLite-compatible schema
 */

import * as fs from 'fs';
import * as path from 'path';

const SCHEMA_PATH = path.join(process.cwd(), 'prisma', 'schema.prisma');
const SQLITE_SCHEMA_PATH = path.join(process.cwd(), 'prisma', '.schema.sqlite.prisma');

const SQLITE_UNSUPPORTED_LIST_SCALARS = new Set([
  'String',
  'Int',
  'BigInt',
  'Float',
  'Decimal',
  'Boolean',
  'DateTime',
  'Bytes',
  'Json',
]);

function parseEnumNames(schemaContent: string): Set<string> {
  const enumNames = new Set<string>();
  const enumRegex = /^\s*enum\s+(\w+)\s*\{/gm;
  let match: RegExpExecArray | null;
  while ((match = enumRegex.exec(schemaContent)) !== null) {
    enumNames.add(match[1]);
  }
  return enumNames;
}

function serializeListDefault(defaultValues: string): string {
  const values = defaultValues
    .split(',')
    .map((value) => value.trim())
    .filter(Boolean)
    .map((value) => value.replace(/^"(.*)"$/, '$1').replace(/^'(.*)'$/, '$1'));

  return `@default("${JSON.stringify(values)}")`;
}

function generateSQLiteSchema() {
  console.log('📝 Generating SQLite schema from PostgreSQL schema...');

  // Read the original schema
  let schemaContent = fs.readFileSync(SCHEMA_PATH, 'utf-8');
  const enumNames = parseEnumNames(schemaContent);

  // Transform the schema for SQLite line by line
  const lines = schemaContent.split('\n');
  const sqliteLines = lines.map(line => {
    // Change provider
    if (line.includes('provider = "postgresql"')) {
      return line.replace('"postgresql"', '"sqlite"');
    }

    // Transform field definitions
    // Match field lines: name Type attributes
    const fieldMatch = line.match(/^(\s+)(\w+)\s+(String\[\]|Json\??)/);
    if (fieldMatch) {
      const indent = fieldMatch[1];
      const fieldName = fieldMatch[2];
      const fieldType = fieldMatch[3];
      const rest = line.substring(fieldMatch[0].length);

      if (fieldType === 'String[]') {
        // String[] -> String with @default("[]")
        if (rest.includes('@default([])')) {
          // Replace @default([]) with @default("[]")
          return `${indent}${fieldName} String${rest.replace('@default([])', '@default("[]")')}`;
        } else {
          // Add @default("[]") before @map if exists, otherwise at the end
          if (rest.includes('@map(')) {
            return `${indent}${fieldName} String @default("[]")${rest}`;
          } else {
            return `${indent}${fieldName} String @default("[]")${rest}`;
          }
        }
      } else if (fieldType === 'Json') {
        // Json -> String with @default("{}")
        if (rest.includes('@default("{}")')) {
          // Already has @default("{}"), just replace Json
          return `${indent}${fieldName} String${rest}`;
        } else if (rest.includes('@default({}')) {
          // Replace @default({}) with @default("{}")
          return `${indent}${fieldName} String${rest.replace('@default({})', '@default("{}")')}`;
        } else {
          // Add @default("{}")
          return `${indent}${fieldName} String @default("{}")${rest}`;
        }
      } else if (fieldType === 'Json?') {
        // Json? -> String? (nullable, no default)
        return `${indent}${fieldName} String?${rest}`;
      }
    }

    // Transform scalar/enum list fields unsupported by SQLite into JSON strings.
    const listFieldMatch = line.match(/^(\s+)(\w+)\s+(\w+)\[\](.*)$/);
    if (listFieldMatch) {
      const indent = listFieldMatch[1];
      const fieldName = listFieldMatch[2];
      const baseType = listFieldMatch[3];
      const rest = listFieldMatch[4];
      const isUnsupportedList = SQLITE_UNSUPPORTED_LIST_SCALARS.has(baseType) || enumNames.has(baseType);

      if (isUnsupportedList) {
        if (rest.includes('@default([')) {
          const defaultMatch = rest.match(/@default\(\[([^\]]*)\]\)/);
          if (defaultMatch) {
            const serializedDefault = serializeListDefault(defaultMatch[1]);
            return `${indent}${fieldName} String${rest.replace(defaultMatch[0], serializedDefault)}`;
          }
        }

        if (rest.includes('@default("[]")')) {
          return `${indent}${fieldName} String${rest}`;
        }

        return `${indent}${fieldName} String @default("[]")${rest}`;
      }
    }

    // Update header comment
    if (line.includes('// Prisma Schema for AuraReserve')) {
      return '// Prisma Schema for AuraReserve - SQLite (AUTO-GENERATED)\n// This file is automatically generated from schema.prisma\n// DO NOT EDIT DIRECTLY - Edit schema.prisma instead';
    }

    return line;
  });

  const sqliteSchema = sqliteLines.join('\n');

  // Write the SQLite schema
  fs.writeFileSync(SQLITE_SCHEMA_PATH, sqliteSchema, 'utf-8');

  console.log('✅ SQLite schema generated successfully!');
  console.log(`📍 Location: ${SQLITE_SCHEMA_PATH}`);
}

// Run the script
try {
  generateSQLiteSchema();
} catch (error) {
  console.error('❌ Error generating SQLite schema:', error);
  process.exit(1);
}
